### PR TITLE
fix: cannot swith to a frame by Browser.switchTo()

### LINKED ISSUE #182: Error thrown when switching to iframe
**Describe the bug**
When attempting to switch context to an iframe that contains some form fields i'm recieving the folllowing error

```
+66s info: ===> Step 'Test: User enters credit card information'
+66s info: ---> wait()
+66s info: ---> wait()
step error -> failed
+66s error:


Error: Could not match frame by name or id: 'easyXDM_default4069_provider'


Detail:
Documentation needed! Please report this at https://github.com/flood-io/element/issues so that we can improve Element!

+66s error: xxxx Step 'Test: User enters credit card information' failed
+66s info: ---> Step 'Test: User enters credit card information' finished
failed, bailing out of steps
+66s info: Iteration completed in 64858ms (walltime)
+66s info: Test completed after 1 iterations
```

**To Reproduce**
1. Go to 'https://www.blinds.com' and simply search for a product add to cart and get all the way to credit card checkout screen where you enter in your information

**Expected behavior**
I'm expected to be able to enter credit card details into the iframe presented in the page

**Desktop (please complete the following information):**
 - OS: macOS
 - Node.js version: 14.4
 - Version: 1.2.3

**code**
```
		await browser.wait(Until.urlContains('Ordering/Checkout/Billing'))
		let iframe = await browser.findElement(By.tagName('iframe'))
		await browser.switchTo().frame(iframe)
```

### PR DESCRIPTION
**Pull request by HieuLeKMS**
resolve #182

### CODE REVIEW

File: packages/core/src/page/ElementHandle.ts [hunk 1]
```diff
@@ -308,7 +311,7 @@ export class ElementHandle implements IElementHandle, Locator {
 			locator = new BaseLocator(new CSSLocator(locator), 'handle.findElement')
 		}
 
-		return locator.find(this.page, this.element)
+		return locator.find(this.page, this.frame, this.element)
```
Comment (andy-flood) [inline packages/core/src/page/ElementHandle.ts:314]: This order makes providing a frame mandatory if you also want to specify an element, which is going to break existing test scripts. It seems like this should go out in a patch release, so we should change the order to keep frame as optional.

**Review by phileba — APPROVED** [review]
